server {
    listen 80;
    server_name 130-61-186-61.sslip.io jobs.naoufal-tb.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 130-61-186-61.sslip.io;

    ssl_certificate     /etc/letsencrypt/live/130-61-186-61.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/130-61-186-61.sslip.io/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/unicorn-scrapper/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri /index.html;
    }
}

server {
    listen 443 ssl;
    server_name jobs.naoufal-tb.online;

    ssl_certificate     /etc/letsencrypt/live/jobs.naoufal-tb.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jobs.naoufal-tb.online/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/unicorn-scrapper/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri /index.html;
    }
}
